name: Deploy Node App

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: 3c970fa0-f80a-4d56-acdb-c3a956ad1095
          tenant-id: d6240b2a-4029-4a82-9f6f-622ea4b2851a
          subscription-id: f3886b36-843f-47a1-a520-86b3699a8245

      - name: Deploy to Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: nodejs-webapp
          package: .
